/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Conexion.Conexion;
import Controller.Render;
import static View.JA_iniciomes.rs;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Becarios
 */
public class JA_iniciomeses extends javax.swing.JInternalFrame {

    public static ResultSet rs;
    private Connection userConn;
    private TableRowSorter trsFiltro;
    private PreparedStatement st;
    public static int idusers;
    Conexion con = new Conexion();
    Connection conn;
    PreparedStatement stmt;
    DefaultTableModel modeloincidenciasjefe = new DefaultTableModel(null, getColumas());
    public static boolean TstVentNvoPres = false;
    public JA_iniciomeses() {
        initComponents();
        this.setResizable(false);
        this.getContentPane().setBackground(new java.awt.Color(51, 102, 255));
        tbIncidencias.setRowHeight(25);
        filas();
        tbIncidencias.setBorder(BorderFactory.createCompoundBorder());
    }

    // clase columanas para el modelo de la tabla 
    private String[] getColumas() {
        String columna[] = {"ID", "Nombre", "Puesto", "Depto", "Detalles"};
        return columna;
    }//fin del clase

    //clase muestra los datos que contrendra la tabla 
    public void filas() {
        tbIncidencias.setDefaultRenderer(Object.class, new Render());
        //añadimos boton a columna de la tabla 
        JButton btn1 = new JButton("Detalles");
        btn1.setName("Detalles");
        //boton
        try {
            String sql = "SELECT emp.empleadoId,emp.nombre,emp.puesto,emp.depto  from empleados emp  LEFT JOIN asignacion asg  ON emp.empleadoId = asg.empleadoId where emp.estatus = 1 AND asg.idUser='" + idusers + "'";
            conn = (this.userConn != null) ? this.userConn : Conexion.getConnection();
            stmt = conn.prepareStatement(sql);
            rs = stmt.executeQuery();
            Object datos[] = new Object[6];
            while (rs.next()) {
                for (int i = 0; i < 6; i++) {
                    datos[0] = rs.getString("empleadoId");
                    datos[1] = rs.getString("nombre");
                    datos[2] = rs.getString("puesto");
                    datos[3] = rs.getString("depto");
                    datos[4] = btn1;
                }
                modeloincidenciasjefe.addRow(datos);
            }
        } catch (Exception e) {
            System.out.println("" + e);
        } finally {
            Conexion.close(rs);
            Conexion.close(stmt);
        }
    } //fin del la clase de filas 

    //clase de filtro de busquueda
    public void filtroBusqueda(JTextField txt) {
        trsFiltro.setRowFilter(RowFilter.regexFilter(txt.getText()));
    }//fin filtro 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbIncidencias = new rojerusan.RSTableMetro();
        txtBuscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbMes = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setTitle("Incidencias mensuales");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(238, 240, 245));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbIncidencias= new rojerusan.RSTableMetro(){
            public boolean  isCellEditable(int rowIndex,int conlIndex ){
                return false;
            }
        };
        tbIncidencias.setModel(modeloincidenciasjefe);
        tbIncidencias.setAltoHead(20);
        tbIncidencias.setColorBackgoundHead(new java.awt.Color(51, 102, 255));
        tbIncidencias.setColorBordeFilas(new java.awt.Color(204, 204, 204));
        tbIncidencias.setColorBordeHead(new java.awt.Color(204, 204, 204));
        tbIncidencias.setColorFilasForeground1(new java.awt.Color(153, 153, 153));
        tbIncidencias.setColorFilasForeground2(new java.awt.Color(153, 153, 153));
        tbIncidencias.setColorSelBackgound(new java.awt.Color(0, 255, 255));
        tbIncidencias.setFuenteFilas(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbIncidencias.setFuenteFilasSelect(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbIncidencias.setFuenteHead(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tbIncidencias.setSelectionBackground(new java.awt.Color(0, 149, 142));
        tbIncidencias.setSurrendersFocusOnKeystroke(true);
        tbIncidencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbIncidenciasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbIncidencias);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1370, 320));

        txtBuscar.setBackground(new java.awt.Color(238, 240, 245));
        txtBuscar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtBuscar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(54, 102, 255)));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        jPanel3.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 250, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/search1.png"))); // NOI18N
        jLabel4.setToolTipText("");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 40, 40));

        cmbMes.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cmbMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione opcion", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        cmbMes.setToolTipText("");
        cmbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMesActionPerformed(evt);
            }
        });
        jPanel3.add(cmbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 247, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Selecciona el Mes:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        txtBuscar.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (txtBuscar.getText()).toUpperCase();
                txtBuscar.setText(cadena);
                repaint();
                filtroBusqueda(txtBuscar);
            }
        });
        trsFiltro = new TableRowSorter(tbIncidencias.getModel());
        tbIncidencias.setRowSorter(trsFiltro);
    }//GEN-LAST:event_txtBuscarKeyTyped

    private void tbIncidenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbIncidenciasMouseClicked
        int column = tbIncidencias.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tbIncidencias.getRowHeight();
        Calendar calendario = Calendar.getInstance();
        if (row < tbIncidencias.getRowCount() && row >= 0 && column < tbIncidencias.getColumnCount() && column >= 0) {
            Object value = tbIncidencias.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;
                if (boton.getName().equals("Detalles")) {
                    int sem = cmbMes.getSelectedIndex();
                    if (sem == 0) {
                        JOptionPane.showMessageDialog(rootPane, "Debe seleccionar el mes !!!", "Precaución", sem, null);
                    } else {
                        try {
                            String nombreusr = tbIncidencias.getValueAt(row, 1).toString();
                            String pof = tbIncidencias.getValueAt(row, 2).toString();
                            String iduser = tbIncidencias.getValueAt(row, 0).toString();
                            String datos = (String) cmbMes.getSelectedItem().toString();
                            String mess = nummes(datos);
                            int numes = Integer.parseInt(mess);
                            int año = calendario.get(Calendar.YEAR);
                            detallesmes dtm = new detallesmes();
                            detallesmes.lblmes.setText(datos);
                            detallesmes.txtnombre.setText(nombreusr);
                            detallesmes.txtidempleado.setText(iduser);
                            dtm.diasiniciales(año, numes, iduser);
                            dtm.setVisible(true);
                        } catch (SQLException ex) {
                            Logger.getLogger(JA_iniciomes.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
            if (value instanceof JCheckBox) {
                JCheckBox ch = (JCheckBox) value;
                if (ch.isSelected() == true) {
                    ch.setSelected(false);
                }
                if (ch.isSelected() == false) {
                    ch.setSelected(true);
                }

            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tbIncidenciasMouseClicked

    private void cmbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMesActionPerformed
        JA_iniciosem inis = new JA_iniciosem();
        inis.limpiar(modeloincidenciasjefe);
        int sem = cmbMes.getSelectedIndex();

        if (sem < 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar ", "Verificar", JOptionPane.WARNING_MESSAGE);
        } else {
            filas();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMesActionPerformed
//clase para identificar el mes

    public String nummes(String num) {
        String numi = "";
        if (num.equalsIgnoreCase("Enero")) {
            numi = "1";
        } else if (num.equalsIgnoreCase("Febrero")) {
            numi = "2";
        } else if (num.equalsIgnoreCase("Marzo")) {
            numi = "3";
        } else if (num.equalsIgnoreCase("Abril")) {
            numi = "4";
        } else if (num.equalsIgnoreCase("Mayo")) {
            numi = "5";
        } else if (num.equalsIgnoreCase("Junio")) {
            numi = "6";
        } else if (num.equalsIgnoreCase("Julio")) {
            numi = "7";
        } else if (num.equalsIgnoreCase("Agosto")) {
            numi = "8";
        } else if (num.equalsIgnoreCase("Septiembre")) {
            numi = "9";
        } else if (num.equalsIgnoreCase("Octubre")) {
            numi = "10";
        } else if (num.equalsIgnoreCase("Noviembre")) {
            numi = "11";
        } else if (num.equalsIgnoreCase("Diciembre")) {
            numi = "12";
        }
        return numi;

    }//fin de clase nummes

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox cmbMes;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSTableMetro tbIncidencias;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
