/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Vertsequer
 */
public class RH_Inicio extends javax.swing.JFrame implements Runnable {

    String hora, minutos, segundos;
    Thread hilo;
    int x, y;
    public static String nombre;
    public static String depto;

    /**
     * Creates new form menu
     */
    public RH_Inicio() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new java.awt.Color(51, 102, 255));
        fecha();
          panellist.setBackground(new Color(0,153,255, 130));
        panelinc.setBackground(new Color(153,255,255,130));
        panelusin.setBackground(new Color(102,255,255,130));
        panelusrcin.setBackground(new Color(102,204,255,130));
        panelperc.setBackground(new Color(0,153,204,130));
        panelsem.setBackground(new Color(102,204,255,130));
        panelusr.setBackground(new Color(153,255,255,130));
        menupanle.setBackground(new Color(0,0,0, 130));
        pnlrelog.setBackground(new Color(0, 0, 0, 130));
        hilo = new Thread(this);
        hilo.start();
        setVisible(true);
       
    }

    public void fecha() {
        Date fechaHoy = new Date();
        SimpleDateFormat formatoEsMX = new SimpleDateFormat(
                "d/MMMM/yyyy", new Locale("ES", "MX"));
        String[] parts = formatoEsMX.format(fechaHoy).split("/");
        String dia = parts[0];
        String mes = parts[1];
        String anio = parts[2];
        lbldia.setText(dia);
        lblmes.setText(mes);
        lblaño.setText(anio);
    }

    public void hora() {
        Calendar calendario = new GregorianCalendar();
        Date horaactual = new Date();
        calendario.setTime(horaactual);
        hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        minutos = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);
    }

    public void run() {
        //while
        Thread current = Thread.currentThread();
        while (current == hilo) {
            hora();
            txthora.setText(hora + ":" + minutos + ":" + segundos);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lblnombrerh = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblcargo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        pnlrelog = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblaño = new javax.swing.JLabel();
        lbldia = new javax.swing.JLabel();
        lblmes = new javax.swing.JLabel();
        logozunfeld = new javax.swing.JLabel();
        txthora = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        menupanle = new javax.swing.JPanel();
        panellist = new javax.swing.JPanel();
        jButton16 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        panelusin = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        panelusrcin = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        panelinc = new javax.swing.JPanel();
        btnIncidencias = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        panelperc = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        panelusr = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        panelsem = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(229, 230, 234));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/portafolio.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/user.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/minimizar.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 32, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/error.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, 32, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/regresar.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 32, 30));

        lblnombrerh.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblnombrerh.setForeground(new java.awt.Color(51, 102, 255));
        jPanel1.add(lblnombrerh, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 230, 20));

        jSeparator3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 230, 10));

        lblcargo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblcargo.setForeground(new java.awt.Color(51, 102, 255));
        jPanel1.add(lblcargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 230, 20));

        jSeparator2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 230, 10));

        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel5MouseDragged(evt);
            }
        });
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 52));

        pnlrelog.setBackground(new java.awt.Color(0, 24, 96));
        pnlrelog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bienvenido");
        pnlrelog.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 50));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("de");
        pnlrelog.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 30, 30));

        lblaño.setFont(new java.awt.Font("Century Gothic", 1, 60)); // NOI18N
        lblaño.setForeground(new java.awt.Color(255, 255, 255));
        pnlrelog.add(lblaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 140, 60));

        lbldia.setBackground(new java.awt.Color(255, 255, 255));
        lbldia.setFont(new java.awt.Font("Century Gothic", 1, 60)); // NOI18N
        lbldia.setForeground(new java.awt.Color(255, 255, 255));
        pnlrelog.add(lbldia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 100, 70));

        lblmes.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblmes.setForeground(new java.awt.Color(255, 255, 255));
        pnlrelog.add(lblmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 80, 30));

        logozunfeld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/logoZunfeld.png"))); // NOI18N
        pnlrelog.add(logozunfeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 80));

        txthora.setEditable(false);
        txthora.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        txthora.setAutoscrolls(false);
        txthora.setBorder(null);
        txthora.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txthora.setEnabled(false);
        pnlrelog.add(txthora, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 140, 50));

        getContentPane().add(pnlrelog, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 460, 490));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 460, 490));

        menupanle.setBackground(new java.awt.Color(0, 24, 96));
        menupanle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panellist.setBackground(new java.awt.Color(0, 153, 255));
        panellist.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton16.setBackground(new java.awt.Color(183, 212, 62));
        jButton16.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton16.setForeground(new java.awt.Color(51, 102, 255));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/lecture.png"))); // NOI18N
        jButton16.setBorder(null);
        jButton16.setBorderPainted(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        panellist.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 80));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Listado Personal");
        panellist.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 130, -1));

        menupanle.add(panellist, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 180, 130));

        panelusin.setBackground(new java.awt.Color(102, 255, 255));
        panelusin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton11.setBackground(new java.awt.Color(242, 182, 146));
        jButton11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(51, 102, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/team.png"))); // NOI18N
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        panelusin.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 80));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Usuarios sin Incidencias ");
        panelusin.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 25));

        menupanle.add(panelusin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 180, 130));

        panelusrcin.setBackground(new java.awt.Color(102, 204, 255));
        panelusrcin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton17.setBackground(new java.awt.Color(177, 224, 234));
        jButton17.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton17.setForeground(new java.awt.Color(51, 102, 255));
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/problem.png"))); // NOI18N
        jButton17.setBorderPainted(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        panelusrcin.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 80));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Usuario con Incidencias");
        panelusrcin.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 25));

        menupanle.add(panelusrcin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 180, 130));

        panelinc.setBackground(new java.awt.Color(102, 204, 255));
        panelinc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIncidencias.setBackground(new java.awt.Color(247, 203, 111));
        btnIncidencias.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnIncidencias.setForeground(new java.awt.Color(51, 102, 255));
        btnIncidencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/test.png"))); // NOI18N
        btnIncidencias.setBorder(null);
        btnIncidencias.setBorderPainted(false);
        btnIncidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncidenciasActionPerformed(evt);
            }
        });
        panelinc.add(btnIncidencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 80));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(" Incidencias");
        panelinc.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        menupanle.add(panelinc, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 180, 130));

        panelperc.setBackground(new java.awt.Color(0, 153, 204));
        panelperc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setBackground(new java.awt.Color(192, 179, 179));
        jButton10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(51, 102, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/form.png"))); // NOI18N
        jButton10.setBorderPainted(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        panelperc.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 80));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Percepciones Deducciones");
        panelperc.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 25));

        menupanle.add(panelperc, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 180, 130));

        panelusr.setBackground(new java.awt.Color(153, 255, 255));
        panelusr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton14.setBackground(new java.awt.Color(97, 209, 182));
        jButton14.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton14.setForeground(new java.awt.Color(51, 102, 255));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/usuarios.png"))); // NOI18N
        jButton14.setBorderPainted(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        panelusr.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 80));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Usuarios ");
        panelusr.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, -1));

        menupanle.add(panelusr, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 180, 130));

        panelsem.setBackground(new java.awt.Color(102, 204, 255));
        panelsem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton13.setBackground(new java.awt.Color(243, 162, 194));
        jButton13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(51, 102, 255));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/calendario.png"))); // NOI18N
        jButton13.setBorderPainted(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        panelsem.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 80));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("  Semanas ");
        panelsem.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        menupanle.add(panelsem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 180, 130));

        getContentPane().add(menupanle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 650, 490));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/background-1634817_960_720.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 650, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.setExtendedState(ICONIFIED);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       String dep = lblcargo.getText();
          String nom = lblnombrerh.getText();
        menuopciones us = new menuopciones();
        us.show(true);
        menuopciones.lblcargo.setText(dep);
        menuopciones.lblnombrerh.setText(nom);
        this.show(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jLabel5MouseDragged

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        String dep = lblcargo.getText();
        String nom = lblnombrerh.getText();

        try {
            RH_ListadoPersonal lis = new RH_ListadoPersonal();
            lis.show();
            RH_ListadoPersonal.lblcargo.setText(dep);
            RH_ListadoPersonal.lblnombrerh.setText(nom);
            this.show(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        String dep = lblcargo.getText();
        String nom = lblnombrerh.getText();
        try {
            RH_UsuariosSinIncidencias usu = new RH_UsuariosSinIncidencias();
            usu.show();
            RH_UsuariosSinIncidencias.lblcargo.setText(dep);
            RH_UsuariosSinIncidencias.lblnombrerh.setText(nom);
            this.show(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        String dep = lblcargo.getText();
        String nom = lblnombrerh.getText();
        try {
            RH_UsuariosConIncidencias usu = new RH_UsuariosConIncidencias();
            usu.show();
            RH_UsuariosConIncidencias.lblcargo.setText(dep);
            RH_UsuariosConIncidencias.lblnombrerh.setText(nom);
            this.show(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void btnIncidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncidenciasActionPerformed
        RH_Incidencias inc = new RH_Incidencias();
        nombre= RH_Inicio.lblnombrerh.getText();
        depto= RH_Inicio.lblcargo.getText();
        inc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIncidenciasActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        String dep = lblcargo.getText();
        String nom = lblnombrerh.getText();
        RH_registrarusrs usur = new RH_registrarusrs();
        RH_registrarusrs.lblnombrejefe.setText(dep);
        RH_registrarusrs.lblcargojefe.setText(nom);
        usur.show();
        this.show(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
     try {
            RH_PercepcionesDeducciones per= new RH_PercepcionesDeducciones();
            per.show();
            RH_PercepcionesDeducciones.lblcargo.setText(lblcargo.getText());
            RH_PercepcionesDeducciones.lblnombrerh.setText(lblnombrerh.getText());
            this.show(false);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Error en: "+ e,"ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
 try {
            RH_SEMANA sema = new RH_SEMANA();
        sema.show();
        this.show(false);
        RH_SEMANA.lblcargo.setText(lblcargo.getText());
        RH_SEMANA.lblnombrerh.setText(lblnombrerh.getText());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error en: "+e,"ERROR",JOptionPane.ERROR_MESSAGE);
        } catch (ParseException ex) {
            Logger.getLogger(RH_Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RH_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RH_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RH_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RH_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RH_Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIncidencias;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblaño;
    public static javax.swing.JLabel lblcargo;
    private javax.swing.JLabel lbldia;
    private javax.swing.JLabel lblmes;
    public static javax.swing.JLabel lblnombrerh;
    private javax.swing.JLabel logozunfeld;
    private javax.swing.JPanel menupanle;
    private javax.swing.JPanel panelinc;
    private javax.swing.JPanel panellist;
    private javax.swing.JPanel panelperc;
    private javax.swing.JPanel panelsem;
    private javax.swing.JPanel panelusin;
    private javax.swing.JPanel panelusr;
    private javax.swing.JPanel panelusrcin;
    private javax.swing.JPanel pnlrelog;
    private javax.swing.JTextField txthora;
    // End of variables declaration//GEN-END:variables
}
