/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import BD.Addusuarios;
import Controller.Eempleados;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Becarios
 */
public class RH_registrarusrs extends javax.swing.JFrame {
DefaultComboBoxModel <Eempleados> modelocmbpersona;

 Addusuarios  eemp;
    public RH_registrarusrs() {
        eemp = new Addusuarios();
        modelocmbpersona = new DefaultComboBoxModel<Eempleados>();
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new java.awt.Color(51, 102, 255));
        SimpleDateFormat dt = new SimpleDateFormat("dd-MM-yyyy");
        Date fechactual = new Date();
        txtfechauser.setText(dt.format(fechactual));
        cargarModeloEmp();
    }

    
    
    
           private void cargarModeloEmp(){
            ArrayList<Eempleados> listaEmp;
        listaEmp = eemp.obtenerEmpleados();
  modelocmbpersona.addElement(new Eempleados(0, "Selecciona opcion", 1,"",""));
        for(Eempleados semana : listaEmp){
            modelocmbpersona.addElement(semana);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtusuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcomtusu = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtdepartamento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcontraseña = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txtfechauser = new javax.swing.JTextField();
        btnguardarusers = new javax.swing.JButton();
        cmbpersonas = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(860, 710));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(229, 230, 234));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 92, 162, 25));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel1.setText("Tipo Usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 139, 82, 20));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel3.setText("Contraseña :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 94, -1, -1));

        jcomtusu.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jcomtusu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un opcion", "Jefe de area", "Recursos Humanos" }));
        jPanel1.add(jcomtusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 139, 162, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel4.setText("Usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 91, 55, 20));
        jPanel1.add(txtdepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 137, 162, 25));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel5.setText("Departamento :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 142, -1, -1));
        jPanel1.add(txtcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 162, 25));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel6.setText("Fecha");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 39, 23));

        txtfechauser.setEditable(false);
        jPanel1.add(txtfechauser, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 162, -1));

        btnguardarusers.setBackground(new java.awt.Color(51, 102, 255));
        btnguardarusers.setForeground(new java.awt.Color(255, 255, 255));
        btnguardarusers.setText("Guardar");
        btnguardarusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarusersActionPerformed(evt);
            }
        });
        jPanel1.add(btnguardarusers, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 179, 132, 42));

        cmbpersonas.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        cmbpersonas.setModel(modelocmbpersona);
        jPanel1.add(cmbpersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 307, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel8.setText("Nombre Persona ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 600, 230));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/adduser.png"))); // NOI18N
        jLabel2.setAlignmentX(0.2F);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 38, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nuevos Usuarios ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 609, 15));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 430, 170));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 420, 170));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Asignados");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 210, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 430, 15));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("No asignados");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 220, -1));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 420, 15));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarusersActionPerformed
 int emp =  cmbpersonas.getSelectedIndex();
 int tuser = jcomtusu.getSelectedIndex();
 Eempleados  empleadod = (Eempleados) cmbpersonas.getSelectedItem();
        if (emp == 0) {
             JOptionPane.showMessageDialog(rootPane, "Seleccione una persona");
        }else if (txtusuario.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(rootPane,"El campo usuario no puede estar vacio");
        }else if(txtcontraseña.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(rootPane,"El campo contraseña no puede estar vacio");
        }else if(tuser==0){
            JOptionPane.showMessageDialog(rootPane, "Elija el tipo de  usuario");
        }else if(txtdepartamento.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(rootPane, "Ingrese el nombre del departamento!!!");
        }else{
            
     try {
         
         String nombre  =  empleadod.getNombre();
         String tipouser = (String) jcomtusu.getSelectedItem();
         int tipousers =0;
         if (tipouser.equalsIgnoreCase("Jefe de area")) {
             tipousers = 0;
         }else if (tipouser.equalsIgnoreCase("Recursos Humanos")){
             tipousers =1;
         }
        eemp.insert(nombre,txtusuario.getText(),txtcontraseña.getText(),tipousers,1,txtdepartamento.getText(),txtfechauser.getText());
        txtcontraseña.setText("");
        txtdepartamento.setText("");
        txtusuario.setText("");
     } catch (SQLException ex) {
         Logger.getLogger(RH_registrarusrs.class.getName()).log(Level.SEVERE, null, ex);
     }
        }
    }//GEN-LAST:event_btnguardarusersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RH_registrarusrs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RH_registrarusrs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RH_registrarusrs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RH_registrarusrs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RH_registrarusrs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardarusers;
    private javax.swing.JComboBox cmbpersonas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox jcomtusu;
    private javax.swing.JPasswordField txtcontraseña;
    private javax.swing.JTextField txtdepartamento;
    private javax.swing.JTextField txtfechauser;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
